"""
Django settings for init project.

Generated by 'django-admin startproject' using Django 3.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
import sys
from dotenv import load_dotenv
from corsheaders.defaults import default_headers
from pathlib import Path

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'subscription',
    'corsheaders',
    'django_crontab',
    'django_elasticsearch_dsl',
    'django_elasticsearch_dsl_drf'
]

SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_BACKEND = "sgbackend.SendGridBackend"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-member-id',
    'x-platform-code',
    'x-version-code',
    'x-username',
    'x-password'
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'large': {
            'format': '%(asctime)s  %(levelname)s  %(filename)s  %(funcName)s  %(lineno)d  %(message)s  '
        },
        'tiny': {
            'format': '%(asctime)s  %(levelname)s %(message)s  '
        }
    },
    'handlers': {
        'file_handler': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'maxBytes': 1024 * 10 * 10,  # 10 MB
            'backupCount': 5,
            'filename': 'logs/custom.log',
            'formatter': 'large',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/subscription.log',
            'maxBytes': 1024 * 10 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'tiny',
        },
        'stream_info_handler': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'json'
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
    },
    'loggers': {
        'stream_info_logger': {
            'handlers': ['stream_info_handler'],
            'level': 'INFO',
            'propagate': False,
        },
        'file_logger': {
            'handlers': ['stream_info_logger', 'file_handler'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['stream_info_logger', 'console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'subscription.middleware.CustomAuthenticateUserID.CustomAuthenticateUserIDMiddleware',
    'subscription.middleware.api_logger.ApiLogger'
]

ROOT_URLCONF = 'init.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'init.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRONJOB_LOG_FILE = ">> " + str(BASE_DIR) + "/scheduled_job.log"
CRONJOBS = [
    ('*/5 * * * *', 'subscription.cron.remove_expired_subscriptions.handle', CRONJOB_LOG_FILE),
    ('*/5 * * * *', 'subscription.cron.send_events.handle', CRONJOB_LOG_FILE)
]
CRONTAB_COMMAND_SUFFIX = '2>&1'

WEBFLOW_KEYS = {
    'collection_id': os.getenv('WEBFLOW_COLLECTION_ID'),
    'api_key': os.getenv('WEBFLOW_API_KEY')
}

ELASTICSEARCH_DSL = {
    'default': {
        'hosts': os.getenv('ELASTIC_SEARCH_HOST'),
        'timeout': 60,
    },
}

# Name of the Elasticsearch index
ELASTICSEARCH_INDEX_NAMES = {
    'subscription.search.subscription_plan_index': 'subscription_plan',
    'subscription.search.subscription_history_index': 'subscription_history'
}

APP_VERSION = "1.1.2"
