import os

from .base import *

DEBUG = True

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

TIME_ZONE = 'Asia/Kolkata'

# variable to check for beta server
IS_BETA = True

URL = os.getenv("DEVELOPMENT_URL")
CORE_SERVICE_URL = os.getenv("DEVELOPMENT_CORE_URL")
WEB_URL = os.getenv('WEB_URL')

ALLOWED_HOSTS = [os.getenv("DEVELOPMENT_ALLOWED_HOST_1"), os.getenv("DEVELOPMENT_ALLOWED_HOST_2")]

RAZORPAY_KEY = os.getenv("DEVELOPMENT_RAZORPAY_KEY")
RAZORPAY_SECRET = os.getenv("DEVELOPMENT_RAZORPAY_SECRET")
RAZORPAY_WEBHOOK_SECRET = os.getenv("DEVELOPMENT_RAZORPAY_WEBHOOK_SECRET")

SEGMENT_KEY = os.getenv("DEVELOPMENT_SEGMENT_KEY")

CRONTAB_DJANGO_SETTINGS_MODULE = 'init.settings.development'

FB_ACCESS_TOKEN = os.getenv("DEVELOPMENT_FB_ACCESS_TOKEN")
FB_PIXEL_ID = os.getenv("DEVELOPMENT_FB_PIXEL_ID")

USE_INTERNAL_FILE_LOGGER = True
OMIT_200_OK_FULL_RESPONSE = False

CORALOGIX_LOGGER = {
    'PRIVATE_API_KEY': os.getenv('DEVELOPMENT_CORALOGIX_LOGGER_PRIVATE_API_KEY'),
    'APPLICATION_NAME': 'LM-SUBSCRIPTIONS-BETA',
    'SUBSYSTEM_NAME_API': 'Backend_App_Api',
    'SUBSYSTEM_NAME_APP': 'Backend_App_System'
}
