apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "skulk-celery"
  namespace: "app-deploy"
  labels:
    app: "skulk-celery"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "skulk-celery"
  template:
    metadata:
      labels:
        app: "skulk-celery"
    spec:
      containers:
      - name: "likeminds-skulk-celery-1"
        image: "asia.gcr.io/likeminds-prod-prj-5464/likeminds-subscription/skulk-celery-prod:v2"
        env:
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: celery-secret
              key: CELERY_BROKER_URL          
