# syntax=docker/dockerfile:1

FROM rabbitmq:3.8.11-management

ADD ./docker-entrypoint/rabbitmq-prod.conf /etc/rabbitmq/rabbitmq.conf
ADD ./docker-entrypoint/definitions-prod.json /etc/rabbitmq/definitions.json

EXPOSE 5672 15672
