PAYMENT_PAGE_AMOUNT_TYPE_FIXED = "fixed"
PAYMENT_PAGE_AMOUNT_TYPE_CUSTOMERS = "customers"

PAYMENT_PAGE_AMOUNT_TYPE_CHOICES = [PAYMENT_PAGE_AMOUNT_TYPE_FIXED, PAYMENT_PAGE_AMOUNT_TYPE_CUSTOMERS]

PAYMENT_PAGE_ASCENDING_ORDER = 0
PAYMENT_PAGE_DESCENDING_ORDER = 1

PAYMENT_PAGE_SORT_ORDER_CHOICES = [PAYMENT_PAGE_ASCENDING_ORDER, PAYMENT_PAGE_DESCENDING_ORDER]