import enum



class SearchIndices(enum.Enum):
    SUBSCRIPTION_PLAN = "subscription_plan"
    SUBSCRIPTION_HISTORY = "subscription_history"


SUBSCRIPTION_PLAN_SUB_TITLE_FIELD = "plan_sub_title"
SUBSCRIPTION_PLAN_MEMBER_SINCE_FIELD = "member_since"


SUBSCRIPTION_PLAN_SUPPORTED_SEARCH_FIELDS = [SUBSCRIPTION_PLAN_SUB_TITLE_FIELD, SUBSCRIPTION_PLAN_MEMBER_SINCE_FIELD]

SUBSCRIPTION_PLAN_FIELDS_DICTIONARY_MAPPING = {
    SUBSCRIPTION_PLAN_SUB_TITLE_FIELD: "plan_sub_title",
    SUBSCRIPTION_PLAN_MEMBER_SINCE_FIELD: "active_user_context.member_since"
}
